openapi: 3.0.3
info:
  title: VolunteerHub API - Mark Notification as Read
  version: 1.0.0
  description: Marks a specific notification as read for the authenticated user.
servers:
  - url: https://volunteerhub.com/api/v1
    description: Production
components:
  $ref: ./components.json
paths:
  /notifications/{notificationId}/read:
    patch:
      tags:
        - Notifications
      summary: Mark notification as read
      operationId: markNotificationRead
      description: Updates the 'read' status of a single notification to 'true'.
      security:
        - bearerAuth: []
      parameters:
        - name: notificationId
          in: path
          required: true
          description: The unique identifier of the notification.
          schema:
            type: string
      responses:
        '200':
          description: Notification marked as read successfully.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/Notification'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'