-- neondb_owner
CREATE USER volunteerhub_app WITH PASSWORD '*********';

GRANT CONNECT ON DATABASE neondb TO volunteerhub_app;
GRANT USAGE ON SCHEMA public TO volunteerhub_app;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO volunteerhub_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO volunteerhub_app;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO volunteerhub_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO volunteerhub_app;
