openapi: 3.0.3
info:
  title: VolunteerHub API Components
  version: 1.0.0
  description: >
    Centralized reusable OpenAPI components for the VolunteerHub API.
    Defines shared schemas, parameters, headers, security schemes, and responses
    used across all API contracts for consistency and scalability.

# ========================
# GLOBAL SECURITY
# ========================
security:
  - bearerAuth: []
  - CookieAuth: []

components:
  # ========================
  # SECURITY SCHEMES
  # ========================
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: >
        JWT-based bearer authentication.
        Include as `Authorization: Bearer <token>` in request headers.

    CookieAuth:
      type: apiKey
      in: cookie
      name: access_token

  # ========================
  # PARAMETERS
  # ========================
  parameters:
    IdParam:
      name: id
      in: path
      required: true
      schema:
        type: string
      description: The unique identifier of the resource.

    EventId:
      name: eventId
      in: path
      required: true
      schema:
        type: string
      description: The unique identifier of an event.

    PostId:
      name: postId
      in: path
      required: true
      schema:
        type: string
      description: The unique identifier of a post.

    CommentId:
      name: commentId
      in: path
      required: true
      schema:
        type: string
      description: The unique identifier of a comment.

    UserId:
      name: userId
      in: path
      required: true
      schema:
        type: string
      description: The unique identifier of a user.

    PaginationPage:
      name: page
      in: query
      schema:
        type: integer
        minimum: 1
        example: 1
      description: The page number for pagination.

    PaginationLimit:
      name: limit
      in: query
      schema:
        type: integer
        minimum: 1
        maximum: 100
        example: 20
      description: The number of items per page.

  # ========================
  # SCHEMAS
  # ========================
  schemas:
    # ---------- Generic ----------
    ApiResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: Operation completed successfully.
        data:
          type: object
          nullable: true
        meta:
          $ref: "#/components/schemas/Meta"

    Error:
      type: object
      properties:
        code:
          type: string
          example: INVALID_REQUEST
        message:
          type: string
          example: Invalid input data
        details:
          type: array
          items:
            type: string

    Meta:
      type: object
      properties:
        total:
          type: integer
          example: 120
        page:
          type: integer
          example: 1
        limit:
          type: integer
          example: 20
        totalPages:
          type: integer
          example: 6

    PaginatedResponse:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
        meta:
          $ref: "#/components/schemas/Meta"

    # ---------- Enum Definitions ----------
    UserRole:
      type: string
      enum: [volunteer, event_manager, admin]
      example: volunteer

    UserStatus:
      type: string
      enum: [pending, active, locked, deleted]
      example: active

    EventStatus:
      type: string
      enum: [pending, approved, ongoing, cancelled, completed]
      example: publish

    EmojiType:
      type: string
      enum: [like, dislike, sad, angry, wow, haha]
      example: like

    NotificationType:
      type: string
      enum: 
        - system        
        - event       
        - user       
      example: system
    
    RegistrationStatus:
      type: string
      enum:
        - pending
        - approved
        - rejected
      example: pending

    ReportType:
      type: string
      enum:
        - spam
        - harassment
        - illegal_content
        - violence
        - copyright_violation
        - other
      example: spam

    Category:
      type: string
      enum:
        - education
        - social
        - technology_stem
        - health_wellness
        - community_service
        - other
      example: social

    # ---------- User & Auth ----------
    User:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        email:
          type: string
          format: email
        role:
          $ref: "#/components/schemas/UserRole"
        status:
          $ref: "#/components/schemas/UserStatus"
        avatarUrl:
          type: string
          nullable: true
        lastLogin:
          type: string
          format: date-time
          nullable: true
      required: [id, username, email, role, status]

    RegisterRequest:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
      required: [username, email, password]

    LoginRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
      required: [email, password]

    AuthResponse:
      type: object
      properties:
        token:
          type: string
        user:
          $ref: "#/components/schemas/User"

    # ---------- Event ----------
    Event:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        location:
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
          nullable: true
        description:
          type: string
        imageUrl:
          type: string
        categories:
          type: array
          items:
            type: string
        registerCount:
          type: integer
        capacity:
          type: integer
        status:
          $ref: "#/components/schemas/EventStatus"
        ownerId:
          type: string
        eventManagerIds:
          type: array
          items:
            type: string
        updatedAt:
          type: string
          format: date-time
      required: [id, name, location, startTime, endTime, description, imageUrl, capacity, status]

    CreateEventRequest:
      type: object
      properties:
        name:
          type: string
        location:
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
          nullable: true
        description:
          type: string
        imageUrl:
          type: string
        categories:
          type: array
          items:
            type: string
        capacity:
          type: integer
      required: [name, location, startTime, endTime, description, capacity]

    UpdateEventRequest:
      type: object
      properties:
        name:
          type: string
        location:
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
          nullable: true
        description:
          type: string
        categories:
          type: array
          items:
            type: string
        capacity:
          type: integer

    EventListResponse:
      allOf:
        - $ref: "#/components/schemas/PaginatedResponse"
        - type: object
          properties:
            data:
              type: array
              items:
                $ref: "#/components/schemas/Event"

    # ---------- Post & Comment ----------
    Post:
      type: object
      properties:
        id:
          type: string
        eventId:
          type: string
        authorId:
          type: string
        content:
          type: string
        imageUrl:
          type: string
        updatedAt:
          type: string
          format: date-time
      required: [id, eventId, authorId, content, updatedAt]

    CreatePostRequest:
      type: object
      properties:
        content:
          type: string
      required: [content]

    UpdatePostRequest:
      type: object
      properties:
        content:
          type: string
        imageUrl:
          type: string

    Comment:
      type: object
      properties:
        id:
          type: string
        postId:
          type: string
        authorId:
          type: string
        content:
          type: string
        updatedAt:
          type: string
          format: date-time
      required: [id, postId, authorId, content, updatedAt]

    CreateCommentRequest:
      type: object
      properties:
        content:
          type: string
      required: [content]

    UpdateCommentRequest:
      type: object
      properties:
        content:
          type: string
      required: [content]

    Reaction:
      type: object
      properties:
        id:
          type: string
        postId:
          type: string
        authorId:
          type: string
        emoji:
          $ref: "#/components/schemas/EmojiType"
      required: [id, postId, authorId, emoji]

    CreateEmojiRequest:
      type: object
      properties:
        emoji:
          $ref: "#/components/schemas/EmojiType"
      required: [emoji]

    UpdateEmojiRequest:
      type: object
      properties:
        emoji:
          $ref: "#/components/schemas/EmojiType"
      required: [type]


    # ---------- Notification ----------
    Notification:
      type: object
      properties:
        id:
          type: string
        type:
          $ref: "#/components/schemas/NotificationType"
        message:
          type: string
        redirectUrl:
          type: string
        read:
          type: boolean
        createdAt:
          type: string
          format: date-time
      required: [id, type, message, read, createdAt]

    # ---------- Health Check ----------
    HealthCheck:
      type: object
      properties:
        status:
          type: string
          example: ok
        uptime:
          type: integer
          example: 345678
        version:
          type: string
          example: 1.0.0

  # ========================
  # HEADERS
  # ========================
  headers:
    X-Request-Id:
      description: Unique identifier for tracing API requests.
      schema:
        type: string
        example: "f7b8c1d4-9e7e-4c9e-8723-1a93f11a3bcb"

    RateLimit-Limit:
      description: The maximum number of requests allowed in the current window.
      schema:
        type: integer
        example: 100

    RateLimit-Remaining:
      description: The number of requests remaining in the current window.
      schema:
        type: integer
        example: 42

    RateLimit-Reset:
      description: The time at which the rate limit resets (in UTC epoch seconds).
      schema:
        type: integer
        example: 1735165200

  # ========================
  # RESPONSES
  # ========================
  responses:
    Ok:
      description: Successful operation
      headers:
        X-Request-Id:
          $ref: "#/components/headers/X-Request-Id"
        X-RateLimit-Limit:
          $ref: "#/components/headers/RateLimit-Limit"
        X-RateLimit-Remaining:
          $ref: "#/components/headers/RateLimit-Remaining"
        X-RateLimit-Reset:
          $ref: "#/components/headers/RateLimit-Reset"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ApiResponse"

    Created:
      description: Resource created successfully
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ApiResponse"

    BadRequest:
      description: Bad Request - Invalid input data
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ValidationError"

    Unauthorized:
      description: Unauthorized - Missing or invalid authentication token
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

    Forbidden:
      description: Forbidden - User lacks required role or permissions
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

    Conflict:
      description: Resource already exists or state conflict
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

    TooManyRequests:
      description: Too Many Requests - Rate limit exceeded
      headers:
        Retry-After:
          description: Seconds until the next request is allowed
          schema:
            type: integer
            example: 60
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
