```yaml
openapi: 3.0.3
info:
  title: VolunteerHub API - Approve User
  version: 1.0.0
  description: Approves a pending user account (admin only).
servers:
  - url: https://volunteerhub.com/api/v1
    description: Production
components:
  $ref: ./components.json
paths:
  /users/{id}/approve:
    patch:
      tags:
        - Admin
      summary: Approve user
      operationId: approveUser
      description: Changes user status to active if pending.
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/UserId'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  $ref: '#/components/schemas/UserStatus'
      responses:
        '200':
          description: User approved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
```