```yaml
openapi: 3.0.3
info:
  title: User API - List Users
  version: 1.0.0
  description: Retrieves a list of all users for admin purposes. May overlap with reporting stats.
servers:
  - url: /api/v1
    description: Base URL for the API
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          example: 123e4567-e89b-12d3-a456-426614174000
        email:
          type: string
          example: user@example.com
        name:
          type: string
          example: John Doe
        status:
          type: string
          enum: [pending, active, locked]
          example: active
        createdAt:
          type: string
          format: date-time
          example: 2025-10-15T14:16:00Z
      required:
        - id
        - email
        - name
        - status
        - createdAt
    Error:
      type: object
      properties:
        code:
          type: string
          example: INVALID_INPUT
        message:
          type: string
          example: Invalid input data
paths:
  /admin/users:
    get:
      tags:
        - Admin
      summary: List all users (admin)
      operationId: listUsers
      description: Retrieves a list of all users for admin purposes. May overlap with reporting stats.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized - Missing or invalid authentication token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - User lacks admin role
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
```