```yaml
openapi: 3.0.3
info:
  title: User API - Register User
  version: 1.0.0
  description: Registers a new user.
servers:
  - url: /api/v1
    description: Base URL for the API
components:
  schemas:
    RegisterRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          format: password
          minLength: 8
          example: Password123!
        name:
          type: string
          example: John Doe
      required:
        - email
        - password
        - name
    AuthResponse:
      type: object
      properties:
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        user:
          type: object
          properties:
            id:
              type: string
              example: 123e4567-e89b-12d3-a456-426614174000
            email:
              type: string
              example: user@example.com
            name:
              type: string
              example: John Doe
    Error:
      type: object
      properties:
        code:
          type: string
          example: INVALID_INPUT
        message:
          type: string
          example: Invalid input data
paths:
  /auth/register:
    post:
      tags:
        - Authentication
      summary: Register a new user
      operationId: registerUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Bad Request - Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Conflict - Email already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
```