```yaml
openapi: 3.0.3
info:
  title: User API - Reset Password
  version: 1.0.0
  description: Resets the user password using the provided reset token.
servers:
  - url: /api/v1
    description: Base URL for the API
components:
  schemas:
    ResetPasswordRequest:
      type: object
      properties:
        token:
          type: string
          example: reset-token-123456
        newPassword:
          type: string
          format: password
          minLength: 8
          example: NewPassword123!
      required:
        - token
        - newPassword
    Error:
      type: object
      properties:
        code:
          type: string
          example: INVALID_INPUT
        message:
          type: string
          example: Invalid input data
paths:
  /auth/reset-password:
    post:
      tags:
        - Authentication
      summary: Reset user password
      operationId: resetPassword
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequest'
      responses:
        '200':
          description: Password successfully reset
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Password successfully reset
        '400':
          description: Bad Request - Invalid or expired token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
```