```yaml
openapi: 3.0.3
info:
  title: User API - Update Profile
  version: 1.0.0
  description: Partially updates the user's profile information.
servers:
  - url: /api/v1
    description: Base URL for the API
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    UpdateProfileRequest:
      type: object
      properties:
        name:
          type: string
          example: Jane Doe
        avatar:
          type: string
          format: uri
          example: https://example.com/avatar.jpg
          nullable: true
    User:
      type: object
      properties:
        id:
          type: string
          example: 123e4567-e89b-12d3-a456-426614174000
        email:
          type: string
          example: user@example.com
        name:
          type: string
          example: John Doe
        status:
          type: string
          enum: [pending, active, locked]
          example: active
        createdAt:
          type: string
          format: date-time
          example: 2025-10-15T14:16:00Z
      required:
        - id
        - email
        - name
        - status
        - createdAt
    Error:
      type: object
      properties:
        code:
          type: string
          example: INVALID_INPUT
        message:
          type: string
          example: Invalid input data
paths:
  /users/{id}/profile:
    patch:
      tags:
        - User
      summary: Partially update user profile
      operationId: updateUserProfile
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProfileRequest'
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad Request - Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - Missing or invalid authentication token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found - User with specified ID does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
```