openapi: 3.0.3
info:
  title: VolunteerHub API – Get Event Participants
  version: 1.0.0
  description: List users participating in an event. Manager / admin only.
servers:
  - url: https://volunteerhub.com/api/v1
    description: Production server
components:
  $ref: ./components.yaml
paths:
  /events/{eventId}/participants:
    get:
      tags: [Events]
      summary: Get participants
      operationId: getParticipants
      description: Returns a list of users who have registered for the event.
      security:
        - bearerAuth: []
      x-rolesAllowed: [manager, admin]
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Participants list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'