openapi: 3.0.3
info:
  title: VolunteerHub API - Export Volunteers
  version: 1.0.0
  description: Admin endpoint to generate and download a CSV file of all volunteers.
servers:
  - url: https://volunteerhub.com/api/v1
    description: Production
components:
  $ref: ./components.json
paths:
  /admin/exports/volunteers:
    get:
      tags:
        - Admin
      summary: Export all volunteers (Admin)
      operationId: adminExportVolunteers
      description: Generates and downloads a CSV file of all 'volunteer' users.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A CSV file of all volunteers.
          headers:
            Content-Disposition:
              description: >-
                Signals the browser to download the file with a specific
                name.
              schema:
                type: string
                example: 'attachment; filename="volunteers-export-2025-10-30.csv"'
          content:
            text/csv:
              schema:
                type: string
                format: binary
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'